CREATE TABLE PINS(
    ID UNIQUEIDENTIFIER default NEWID()
        CONSTRAINT [PK_PIN_ID] 
        PRIMARY KEY CLUSTERED,
    USER_ID UNIQUEIDENTIFIER default NEWID()
        CONSTRAINT FK_USER_ID
        REFERENCES USERS(ID),
    LATITUDE DECIMAL(6,5),
    LONGITUDE DECIMAL(6,5),
    LABEL NVARCHAR(512),
    CREATE_DATE DATETIME
);

/* 
DROP TABLE PINS; 
*/